name: overlay_screen
description: A Flutter plugin to easily display and dispose overlay screens anywhere in your app.
version: 1.2.0+1-nullsafety.0
homepage: https://github.com/JosLuna98/overlay_screen.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.jostech.overlay_screen
        pluginClass: OverlayScreenPlugin
      ios:
        pluginClass: OverlayScreenPlugin
